

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(969, 667)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.dosya_yukle = QtWidgets.QPushButton(self.centralwidget)
        self.dosya_yukle.setGeometry(QtCore.QRect(340, 430, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dosya_yukle.setFont(font)
        self.dosya_yukle.setObjectName("dosya_yukle")
        self.baslat = QtWidgets.QPushButton(self.centralwidget)
        self.baslat.setGeometry(QtCore.QRect(250, 590, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.baslat.setFont(font)
        self.baslat.setObjectName("baslat")
        self.kupon_id_label_6 = QtWidgets.QLabel(self.centralwidget)
        self.kupon_id_label_6.setGeometry(QtCore.QRect(30, 200, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.kupon_id_label_6.setFont(font)
        self.kupon_id_label_6.setObjectName("kupon_id_label_6")
        self.kupon_id_label_5 = QtWidgets.QLabel(self.centralwidget)
        self.kupon_id_label_5.setGeometry(QtCore.QRect(40, 430, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.kupon_id_label_5.setFont(font)
        self.kupon_id_label_5.setObjectName("kupon_id_label_5")
        self.dersinadi = QtWidgets.QTextEdit(self.centralwidget)
        self.dersinadi.setGeometry(QtCore.QRect(180, 200, 381, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dersinadi.setFont(font)
        self.dersinadi.setObjectName("dersinadi")
        self.cevapanahtari = QtWidgets.QTableWidget(self.centralwidget)
        self.cevapanahtari.setGeometry(QtCore.QRect(610, 10, 311, 591))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.cevapanahtari.setFont(font)
        self.cevapanahtari.setObjectName("cevapanahtari")
        self.cevapanahtari.setColumnCount(2)
        self.cevapanahtari.setRowCount(40)
        item = QtWidgets.QTableWidgetItem()
        self.cevapanahtari.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cevapanahtari.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cevapanahtari.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.cevapanahtari.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.cevapanahtari.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.cevapanahtari.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.cevapanahtari.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.cevapanahtari.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.cevapanahtari.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.cevapanahtari.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.cevapanahtari.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.cevapanahtari.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.cevapanahtari.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.cevapanahtari.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.cevapanahtari.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.cevapanahtari.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.cevapanahtari.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.cevapanahtari.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.cevapanahtari.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.cevapanahtari.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.cevapanahtari.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.cevapanahtari.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.cevapanahtari.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.cevapanahtari.setVerticalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.cevapanahtari.setVerticalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.cevapanahtari.setVerticalHeaderItem(25, item)
        item = QtWidgets.QTableWidgetItem()
        self.cevapanahtari.setVerticalHeaderItem(26, item)
        item = QtWidgets.QTableWidgetItem()
        self.cevapanahtari.setVerticalHeaderItem(27, item)
        item = QtWidgets.QTableWidgetItem()
        self.cevapanahtari.setVerticalHeaderItem(28, item)
        item = QtWidgets.QTableWidgetItem()
        self.cevapanahtari.setVerticalHeaderItem(29, item)
        item = QtWidgets.QTableWidgetItem()
        self.cevapanahtari.setVerticalHeaderItem(30, item)
        item = QtWidgets.QTableWidgetItem()
        self.cevapanahtari.setVerticalHeaderItem(31, item)
        item = QtWidgets.QTableWidgetItem()
        self.cevapanahtari.setVerticalHeaderItem(32, item)
        item = QtWidgets.QTableWidgetItem()
        self.cevapanahtari.setVerticalHeaderItem(33, item)
        item = QtWidgets.QTableWidgetItem()
        self.cevapanahtari.setVerticalHeaderItem(34, item)
        item = QtWidgets.QTableWidgetItem()
        self.cevapanahtari.setVerticalHeaderItem(35, item)
        item = QtWidgets.QTableWidgetItem()
        self.cevapanahtari.setVerticalHeaderItem(36, item)
        item = QtWidgets.QTableWidgetItem()
        self.cevapanahtari.setVerticalHeaderItem(37, item)
        item = QtWidgets.QTableWidgetItem()
        self.cevapanahtari.setVerticalHeaderItem(38, item)
        item = QtWidgets.QTableWidgetItem()
        self.cevapanahtari.setVerticalHeaderItem(39, item)
        item = QtWidgets.QTableWidgetItem()
        self.cevapanahtari.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cevapanahtari.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cevapanahtari.setItem(0, 0, item)
        self.dosya_yukle_2 = QtWidgets.QPushButton(self.centralwidget)
        self.dosya_yukle_2.setGeometry(QtCore.QRect(340, 510, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dosya_yukle_2.setFont(font)
        self.dosya_yukle_2.setObjectName("dosya_yukle_2")
        self.kupon_id_label_9 = QtWidgets.QLabel(self.centralwidget)
        self.kupon_id_label_9.setGeometry(QtCore.QRect(30, 280, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.kupon_id_label_9.setFont(font)
        self.kupon_id_label_9.setObjectName("kupon_id_label_9")
        self.sorusayisi = QtWidgets.QTextEdit(self.centralwidget)
        self.sorusayisi.setGeometry(QtCore.QRect(180, 280, 381, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sorusayisi.setFont(font)
        self.sorusayisi.setObjectName("sorusayisi")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(340, 360, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.kupon_id_label_7 = QtWidgets.QLabel(self.centralwidget)
        self.kupon_id_label_7.setGeometry(QtCore.QRect(40, 510, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.kupon_id_label_7.setFont(font)
        self.kupon_id_label_7.setObjectName("kupon_id_label_7")
        self.resim = QtWidgets.QLabel(self.centralwidget)
        self.resim.setGeometry(QtCore.QRect(170, 40, 251, 131))
        self.resim.setText("")
        self.resim.setObjectName("resim")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.dosya_yukle.setText(_translate("MainWindow", "Dosya Seç"))
        self.baslat.setText(_translate("MainWindow", "Başlat"))
        self.kupon_id_label_6.setText(_translate("MainWindow", "Dersin Adı:"))
        self.kupon_id_label_5.setText(_translate("MainWindow", "Cevap Anahtarı Yükle"))
        item = self.cevapanahtari.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.cevapanahtari.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.cevapanahtari.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.cevapanahtari.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.cevapanahtari.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.cevapanahtari.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.cevapanahtari.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.cevapanahtari.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.cevapanahtari.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.cevapanahtari.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "10"))
        item = self.cevapanahtari.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "11"))
        item = self.cevapanahtari.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "12"))
        item = self.cevapanahtari.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "13"))
        item = self.cevapanahtari.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "14"))
        item = self.cevapanahtari.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "15"))
        item = self.cevapanahtari.verticalHeaderItem(15)
        item.setText(_translate("MainWindow", "16"))
        item = self.cevapanahtari.verticalHeaderItem(16)
        item.setText(_translate("MainWindow", "17"))
        item = self.cevapanahtari.verticalHeaderItem(17)
        item.setText(_translate("MainWindow", "18"))
        item = self.cevapanahtari.verticalHeaderItem(18)
        item.setText(_translate("MainWindow", "19"))
        item = self.cevapanahtari.verticalHeaderItem(19)
        item.setText(_translate("MainWindow", "20"))
        item = self.cevapanahtari.verticalHeaderItem(20)
        item.setText(_translate("MainWindow", "21"))
        item = self.cevapanahtari.verticalHeaderItem(21)
        item.setText(_translate("MainWindow", "22"))
        item = self.cevapanahtari.verticalHeaderItem(22)
        item.setText(_translate("MainWindow", "23"))
        item = self.cevapanahtari.verticalHeaderItem(23)
        item.setText(_translate("MainWindow", "24"))
        item = self.cevapanahtari.verticalHeaderItem(24)
        item.setText(_translate("MainWindow", "25"))
        item = self.cevapanahtari.verticalHeaderItem(25)
        item.setText(_translate("MainWindow", "26"))
        item = self.cevapanahtari.verticalHeaderItem(26)
        item.setText(_translate("MainWindow", "27"))
        item = self.cevapanahtari.verticalHeaderItem(27)
        item.setText(_translate("MainWindow", "28"))
        item = self.cevapanahtari.verticalHeaderItem(28)
        item.setText(_translate("MainWindow", "29"))
        item = self.cevapanahtari.verticalHeaderItem(29)
        item.setText(_translate("MainWindow", "30"))
        item = self.cevapanahtari.verticalHeaderItem(30)
        item.setText(_translate("MainWindow", "31"))
        item = self.cevapanahtari.verticalHeaderItem(31)
        item.setText(_translate("MainWindow", "32"))
        item = self.cevapanahtari.verticalHeaderItem(32)
        item.setText(_translate("MainWindow", "33"))
        item = self.cevapanahtari.verticalHeaderItem(33)
        item.setText(_translate("MainWindow", "34"))
        item = self.cevapanahtari.verticalHeaderItem(34)
        item.setText(_translate("MainWindow", "35"))
        item = self.cevapanahtari.verticalHeaderItem(35)
        item.setText(_translate("MainWindow", "36"))
        item = self.cevapanahtari.verticalHeaderItem(36)
        item.setText(_translate("MainWindow", "37"))
        item = self.cevapanahtari.verticalHeaderItem(37)
        item.setText(_translate("MainWindow", "38"))
        item = self.cevapanahtari.verticalHeaderItem(38)
        item.setText(_translate("MainWindow", "39"))
        item = self.cevapanahtari.verticalHeaderItem(39)
        item.setText(_translate("MainWindow", "40"))
        item = self.cevapanahtari.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Cevaplar"))
        item = self.cevapanahtari.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Puanlar"))
        __sortingEnabled = self.cevapanahtari.isSortingEnabled()
        self.cevapanahtari.setSortingEnabled(False)
        self.cevapanahtari.setSortingEnabled(__sortingEnabled)
        self.dosya_yukle_2.setText(_translate("MainWindow", "Klasör Seç"))
        self.kupon_id_label_9.setText(_translate("MainWindow", "Soru Sayısı:"))
        self.comboBox.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox.setItemText(7, _translate("MainWindow", "8"))
        self.comboBox.setItemText(8, _translate("MainWindow", "9"))
        self.comboBox.setItemText(9, _translate("MainWindow", "10"))
        self.comboBox.setItemText(10, _translate("MainWindow", "11"))
        self.comboBox.setItemText(11, _translate("MainWindow", "12"))
        self.comboBox.setItemText(12, _translate("MainWindow", "13"))
        self.comboBox.setItemText(13, _translate("MainWindow", "14"))
        self.comboBox.setItemText(14, _translate("MainWindow", "15"))
        self.kupon_id_label_7.setText(_translate("MainWindow", "Soruların Klasörünü Seç"))

